-- Enable Row Level Security
alter table profiles enable row level security;
alter table ideas enable row level security;
alter table messages enable row level security;
alter table contracts enable row level security;

-- Profiles Table
create table if not exists profiles (
  id uuid references auth.users on delete cascade primary key,
  user_type text check (user_type in ('idea', 'skill', 'investor')),
  full_name text,
  avatar_url text,
  onboarding_data jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Ideas Table
create table if not exists ideas (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  title text not null,
  description text not null,
  sector text not null,
  funding_needed text,
  equity_offered text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Messages Table
create table if not exists messages (
  id bigint generated by default as identity primary key,
  sender_id uuid references profiles(id) on delete cascade not null,
  receiver_id uuid references profiles(id) on delete cascade not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Contracts Table
create table if not exists contracts (
  id bigint generated by default as identity primary key,
  idea_id bigint references ideas(id) on delete cascade not null,
  founder_id uuid references profiles(id) on delete cascade not null,
  investor_id uuid references profiles(id) on delete cascade not null,
  amount text not null,
  equity text not null,
  status text default 'pending' check (status in ('pending', 'signed', 'rejected')),
  pdf_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies

-- Profiles: Public read, Owner update
create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Ideas: Public read, Owner update/delete
create policy "Ideas are viewable by everyone."
  on ideas for select
  using ( true );

create policy "Users can insert their own ideas."
  on ideas for insert
  with check ( auth.uid() = user_id );

create policy "Users can update own ideas."
  on ideas for update
  using ( auth.uid() = user_id );

-- Messages: Sender and Receiver read, Sender insert
create policy "Users can read their own messages."
  on messages for select
  using ( auth.uid() = sender_id or auth.uid() = receiver_id );

create policy "Users can send messages."
  on messages for insert
  with check ( auth.uid() = sender_id );

-- Contracts: Parties read, Parties update
create policy "Users can read their own contracts."
  on contracts for select
  using ( auth.uid() = founder_id or auth.uid() = investor_id );

create policy "Users can update their own contracts."
  on contracts for update
  using ( auth.uid() = founder_id or auth.uid() = investor_id );
