-- Enable Extensions
create extension if not exists vector;

-- Enable Row Level Security
alter table profiles enable row level security;
alter table ideas enable row level security;
alter table messages enable row level security;
alter table contracts enable row level security;

-- Profiles Table
create table if not exists profiles (
  id uuid references auth.users on delete cascade primary key,
  user_type text check (user_type in ('idea', 'skill', 'investor')),
  full_name text,
  avatar_url text,
  onboarding_data jsonb,
  raed_score integer default 0,
  xp integer default 0,
  level integer default 1,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Ideas Table
create table if not exists ideas (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  title text not null,
  description text not null,
  sector text not null,
  funding_needed text,
  equity_offered text,
  is_locked boolean default false,
  raed_score integer,
  stage text,
  embedding vector(768), -- For text-embedding-004
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Messages Table
create table if not exists messages (
  id bigint generated by default as identity primary key,
  sender_id uuid references profiles(id) on delete cascade not null,
  receiver_id uuid references profiles(id) on delete cascade not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Contracts Table
create table if not exists contracts (
  id uuid default gen_random_uuid() primary key,
  idea_id bigint references ideas(id) on delete cascade,
  founder_id uuid references profiles(id) on delete cascade,
  investor_id uuid references profiles(id) on delete cascade,
  parties jsonb not null default '[]',
  terms text not null default '',
  amount text,
  equity text,
  signed boolean default false,
  status text default 'pending' check (status in ('pending', 'signed', 'rejected')),
  pdf_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Tasks Table
create table if not exists tasks (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  idea_id bigint references ideas(id) on delete cascade,
  title text not null,
  status text default 'todo' check (status in ('todo', 'in-progress', 'done')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Notifications Table
create table if not exists notifications (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  title text not null,
  content text not null,
  type text not null,
  read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Market Cache Table
create table if not exists market_cache (
  keyword text primary key,
  trend_data jsonb not null,
  last_fetched timestamp with time zone default timezone('utc'::text, now()) not null
);

-- NDAs Table
create table if not exists ndas (
  id uuid default gen_random_uuid() primary key,
  idea_id bigint references ideas(id) on delete cascade,
  user_id uuid references profiles(id) on delete cascade,
  accepted_at timestamp with time zone default timezone('utc'::text, now()) not null,
  ip_address text
);

-- Idea Timestamps (Idea Vault)
create table if not exists idea_timestamps (
  id uuid default gen_random_uuid() primary key,
  idea_id bigint references ideas(id) on delete cascade,
  hash text not null,
  verified_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Functions
create or replace function match_ideas (
  query_embedding vector(768),
  match_threshold float,
  match_count int
)
returns table (
  id bigint,
  title text,
  description text,
  sector text,
  similarity float
)
language plpgsql
as $$
begin
  return query
  select
    ideas.id,
    ideas.title,
    ideas.description,
    ideas.sector,
    1 - (ideas.embedding <=> query_embedding) as similarity
  from ideas
  where 1 - (ideas.embedding <=> query_embedding) > match_threshold
  order by ideas.embedding <=> query_embedding
  limit match_count;
end;
$$;

-- RLS Policies
alter table tasks enable row level security;
alter table notifications enable row level security;
alter table ndas enable row level security;
alter table idea_timestamps enable row level security;

-- Policies
create policy "Users can manage their own tasks." on tasks for all using ( auth.uid() = user_id );
create policy "Users can manage their own notifications." on notifications for all using ( auth.uid() = user_id );
create policy "Users can read their own NDAs." on ndas for select using ( auth.uid() = user_id );
create policy "Users can insert their own NDAs." on ndas for insert with check ( auth.uid() = user_id );
create policy "Users can read idea timestamps." on idea_timestamps for select using ( true );

-- Profiles: Public read, Owner update
create policy "Public profiles are viewable by everyone." on profiles for select using ( true );
create policy "Users can insert their own profile." on profiles for insert with check ( auth.uid() = id );
create policy "Users can update own profile." on profiles for update using ( auth.uid() = id );

-- Ideas: Public read, Owner update/delete
create policy "Ideas are viewable by everyone." on ideas for select using ( true );
create policy "Users can insert their own ideas." on ideas for insert with check ( auth.uid() = user_id );
create policy "Users can update own ideas." on ideas for update using ( auth.uid() = user_id );

-- Messages: Sender and Receiver read, Sender insert
create policy "Users can read their own messages." on messages for select using ( auth.uid() = sender_id or auth.uid() = receiver_id );
create policy "Users can send messages." on messages for insert with check ( auth.uid() = sender_id );

-- Contracts: Parties read, Parties update
create policy "Users can read their own contracts." on contracts for select using ( auth.uid() = founder_id or auth.uid() = investor_id );
create policy "Users can update their own contracts." on contracts for update using ( auth.uid() = founder_id or auth.uid() = investor_id );
